"""add_unique_bot_chat_binding

Revision ID: d11e485f990a
Revises: 67327aa41e4b
Create Date: 2026-03-24 14:37:22.740092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd11e485f990a'
down_revision: Union[str, Sequence[str], None] = '67327aa41e4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_bot_chat', 'bot_chat_bindings', ['bot_id', 'chat_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_bot_chat', 'bot_chat_bindings', type_='unique')
    # ### end Alembic commands ###
